pc10[0]="A"
sw1[0]="A"

pc11[0]="B"
sw1[1]="B"

pc12[0]="C"
sw1[2]="C"

pc13[0]="D"
sw2[0]="D"

pc14[0]="E"
sw2[1]="E"

pc15[0]="F"
sw2[2]="F"

dhcp[0]="G"
sw3[0]="G"

dns[0]="H"
sw3[1]="H"

web[0]="I"
sw3[2]="I"

sw1[3]="J"
sw2[3]="J"

sw2[4]="K"
sw3[3]="K"

router[0]="L"
sw1[4]="L"

router[1]="M"
sw1[5]="M"

router[2]="N"
sw1[6]="N"